# Copyright (C) 2026 AERA Recovery Project contributors
# SPDX-License-Identifier: GPL-3.0-or-later

AERA_MAINTAINER := Jonas Salo
AERA_SCREEN_H := 2376
AERA_STATUS_H := 120
AERA_HIDE_NOTCH := 1
AERA_STATUS_INDENT_LEFT := 50
AERA_STATUS_INDENT_RIGHT := 30
AERA_OPTIONS_LIST_NUM := 6
AERA_USE_GREEN_LED := 0

AERA_ENABLE_ALL_PARTITION_TOOLS := 1
AERA_WORKAROUND_BACKUP_BUG := 1
AERA_USE_AIDL_BOOT_CONTROL := 1
AERA_FORCE_DATA_FORMAT_F2FS := 1
AERA_UNBIND_SDCARD_F2FS := 1
AERA_WIPE_METADATA_AFTER_DATAFORMAT := 1
AERA_DYNAMIC_FULL_SIZE := 14578294784
AERA_DISPLAY_FORMAT_FILESYSTEMS_DEBUG_INFO := 1
AERA_FORCE_PREBUILT_KERNEL := 1
AERA_NO_RELOAD_AFTER_DECRYPTION := 1
AERA_NO_TREBLE_COMPATIBILITY_CHECK := 1
AERA_AB_DEVICE_WITH_RECOVERY_PARTITION := 1
AERA_ENABLE_FRP_ADDON := 1
AERA_USE_LZ4_COMPRESSION := 1
AERA_ENABLE_FS_COMPRESSION := 1
AERA_ENABLE_WLAN := 1
#
